### ISSUE TITLE
File with binary names are created

### ISSUE THREAD

**Issue by ComradeKeys** [R4stl1n/cAudio#47] opened 2016-10-10 04:58 UTC
I believe this was caused by my pull request, anyways in a cAudio application there will occasionally be files created that have strange names (in binary?) that contain the normal contents of cAudioEngine.html however in different files. There must of been file I/O happening involving logging in a place that I did not find. This should be fixed at some point as it makes it difficult to create something professional with cAudio if it places files in the current directory, this was why I tried changing the logging system in the first place.
For bonus points the logging could of been redone with easyloggingpp if you ever get the time to move it over, this is a helpful logger because it outputs to the screen and to a file and is very configurable (plus it is MIT licensed). It would be great to include it as the logging system for the next version of cAudio.
https://github.com/easylogging/easyloggingpp/
It even supports colored output now :) If in the event you do not get time towards the end of the release of my game I will fix it myself, however it would be nice if upstream did this on it's own.

**Comment by ComradeKeys** [comment] 2016-10-10 04:59
![selection_197](https://cloud.githubusercontent.com/assets/12195202/19227210/c37613ee-8e84-11e6-8aac-c4c3b83a8050.png)
Here is a screenshot of what the files look like for me, my friends are having similar issues.

**Comment by Deathsbreed** [comment] 2016-10-10 10:32
Also, these files can't be deleted with the `rm` command either, since those names that appear in the terminal (via `ls`) are not their real names. When I opened up the file manager it said that they were in an _invalid encoding_, which basically means that it's some kind of binary output or something similar (as @ComradeKeys points out).

**Comment by R4stl1n** [comment] 2016-10-13 22:35
This is very interesting... as there isn't any file io being done other than the logger... does this occur if you completely disable logging?

**Comment by ComradeKeys** [comment] 2016-10-14 22:01
I have not tried yet; what is the option to disable logging in cAudio?

**Comment by ComradeKeys** [comment] 2016-10-29 19:01
If you disable logging (by not putting a file name when initializing the audiomanager) then it will go back to it's old behavior of putting cAudioEngineLogs.html in the current directory. Is there any news on getting this problem solved?

**Comment by R4stl1n** [comment] 2016-11-01 05:31
Unfortunately i currently have not had the free time to work on this. If it was indeed your changes i think you might have a better idea of where to start.

**Comment by R4stl1n** [comment] 2016-11-01 05:59
Just attempted to recreate this issue on macosx... I cannot seem to get random arbitrary binary file names. Also reviewing the code i don't see why there would be a time when that could happen. Maybe you have some funny pointer issue going on in your application that causes the filename variable to be over written with random binary?

**Comment by R4stl1n** [comment] 2016-11-01 20:31
Also i just attempted this on a linux vm *Ubuntu 16.04* and can not reproduce.

**Comment by ComradeKeys** [comment] 2016-11-01 20:34
An issue might be that our game is playing sounds repeatedly; where most
of the samples play a sound once. Have you tried letting it play for a
few minutes?

**Comment by R4stl1n** [comment] 2016-11-01 21:13
I have tested using the Tutorial1_2d and the Tutorial7_CustomFileLogger. Anyway you can create a minimal example that causes the issue?

**Comment by R4stl1n** [comment] 2016-11-21 15:55
Going to close this ticket as there isn't any follow up.

**Closed by R4stl1n** 2016-11-21 15:55 UTC

**Comment by bkeys** [comment] 2016-12-14 10:22
Sorry about not getting back, in our project this happens by simply opening the game and closing it; the binary files are created. I am unsure if other people are running into the same issues as I am.
